image: immcantation/test:devel 
pipelines:
  default:
    - step:
        name: Test
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
    - step:
        name: Update immcantation/suite:devel
        script:
          - curl -H "Content-Type:\ application/json" --data '{"docker_tag":\ "devel"}' -X POST https://hub.docker.com/api/build/v1/source/${DOCKERHUB_REPO}/trigger/${DOCKERHUB_TRIGGER}/call/