pipelines:
  default:
    - step:
        name: Test
        image: immcantation/test:devel
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
    - step:
        name: Update immcantation/suite:devel
        script:
          - curl -H "Content-Type:application/json" --data '{"docker_tag":"devel"}' -X POST https://hub.docker.com/api/build/v1/source/${DOCKERHUB_REPO}/trigger/${DOCKERHUB_TRIGGER}/call/
  custom:
    airrflow:
      - step:
          name: Test nf-core/airrflow
          script:
            - wget -qO- https://get.nextflow.io | bash && chmod +x nextflow
            - ./nextflow run nf-core/airrflow -r enchantr-0.1.5 -profile test_assembled_immcantation_devel_hs,docker --max_memory 4.GB --outdir ./results
          services:
            - docker
