pipelines:
  default:
    - step:
        name: Test
        image:
            name: immcantation/test:devel 
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
    - step:
        name: Update and push immcantation/suite:devel
        image:
            name: immcantation/suite:devel
        script:
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker build -t immcantation/suite:devel -f docker/Dockerfile .
          - docker push immcantation/suite:devel
        services:
          - docker
definitions:
  services:
    docker:
      memory: 3072