pipelines:
  default:
    - step:
        name: Test
        image: immcantation/test:devel
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
    - step:
        name: Update immcantation/suite:devel
        script:
          - curl -H "Content-Type:application/json" --data '{"docker_tag":"devel"}' -X POST https://hub.docker.com/api/build/v1/source/${DOCKERHUB_REPO}/trigger/${DOCKERHUB_TRIGGER}/call/
  custom:
    airrflow:
    # Does not work with atlassian/default-image:4.20230726 and docker profile. Docker-in-Docker issue with Nextflow?: In Bitbucket Pipelines, we don't yet support adding volumes other than BITBUCKET_CLONE_DIR
    # https://confluence.atlassian.com/bbkb/docker-error-authorization-denied-by-plugin-pipelines-command-not-supported-1142238807.html and Nextflow tries to add other folders
    # Use immcantation/suite:devel and local executor
      - step:
          name: Test nf-core/airrflow
          image: immcantation/suite:devel
          script:
            - dnf install -y java-17-openjdk
            - update-alternatives --install  /usr/bin/python python /usr/bin/python3 1
            - export PYTHONPATH=/usr/local/lib/python3.11/site-packages
            - wget -qO- https://get.nextflow.io | bash && chmod +x nextflow
            - ./nextflow run nf-core/airrflow -r enchantr-0.1.5 -c tests/airrflow/airrflow.config --outdir ./results
          artifacts: # defining the artifacts to be passed to each future step.
            - results
