pipelines:
  default:
    - step:
        name: Test
        image:
            name: immcantation/test:devel 
        script:
          - sed -i '/test/ d' .Rbuildignore
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings            
    - step:
        name: Update and push immcantation/suite:devel
        image:
            name: immcantation/suite:devel
        script:
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker build -t immcantation/suite:devel -f docker/Dockerfile .
          - docker push immcantation/suite:devel
        services:
          - docker:
              memory: 3072